# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Lantern' do
pod 'RCTMapboxGL', :path => 'node_modules/react-native-mapbox-gl/ios'
end

target 'LanternTests' do

end

